export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const SET_IS_LOGIN = 'SET_IS_LOGIN'
export const COOKIE_TO_SESSION = 'COOKIE_TO_SESSION'
export const REMOVE_SESSION = 'REMOVE_SESSION'
export const REMOVE_IS_LOGIN = 'REMOVE_IS_LOGIN'
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_TARGET_LIST = 'FETCH_TARGET_LIST'

export const FETCH_COMMENT_LIST = 'FETCH_COMMENT_LIST'
export const FETCH_COMMENT = "FETCH_COMMENT"

export const FETCH_REPLY_LIST = 'FETCH_REPLY_LIST'
export const FETCH_COMMENT_LIKES = "FETCH_COMMENT_LIKES"
export const SET_MEMBER_NO = 'SET_MEMBER_NO'
export const FIND_MEMBER_INFO = 'FIND_MEMBER_INFO'
export const GET_NOTICE_LIST = 'GET_NOTICE_LIST'
export const GET_NOTICE = 'GET_NOTICE'
export const SET_AUTH = 'SET_AUTH'
