export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const SET_IS_LOGIN = 'SET_IS_LOGIN'
export const COOKIE_TO_SESSION = 'COOKIE_TO_SESSION'
export const REMOVE_SESSION = 'REMOVE_SESSION'
export const REMOVE_IS_LOGIN = 'REMOVE_IS_LOGIN'
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_TARGET_LIST = 'FETCH_TARGET_LIST'

export const FETCH_COMMENT_LIST = 'FETCH_COMMENT_LIST'
export const FETCH_COMMENT = "FETCH_COMMENT"


export const FETCH_REPLY_LIST = 'FETCH_REPLY_LIST'
export const FETCH_COMMENT_LIKES = "FETCH_COMMENT_LIKES"
export const SET_MEMBER_NO = 'SET_MEMBER_NO'
export const FIND_MEMBER_INFO = 'FIND_MEMBER_INFO'
export const GET_NOTICE_LIST = 'GET_NOTICE_LIST'
export const GET_NOTICE = 'GET_NOTICE'
export const SET_AUTH = 'SET_AUTH'
export const SET_CARD_MODE = 'SET_CARD_MODE'
export const SET_TABLE_MODE = 'SET_TABLE_MODE'
export const GET_REPORTED_BOARD_LIST = "GET_REPORTED_BOARD_LIST"

export const GET_REPORTED_COMMENT_LIST = 'GET_REPORTED_COMMENT_LIST'
export const SET_ITEM_LIST = 'SET_ITEM_LIST'

export const FETCH_MY_BOARD_LIST = 'FETCH_MY_BOARD_LIST'
export const FETCH_MY_COMMENT_LIST = 'FETCH_MY_COMMENT_LIST'

export const FETCH_MY_LIKE_LIST = 'FETCH_MY_LIKE_LIST'
export const GET_MY_PARKING_STATES = 'GET_MY_PARKING_STATES'

export const FETCH_NEWS = 'FETCH_NEWS'
